apiVersion: v2
name: novu
description: A Helm chart for self-hosted Novu notification center
type: application
version: 1.0.0
appVersion: "2.1.0"

dependencies:
  - name: valkey
    alias: redis
    version: "0.9.4"
    repository: "https://valkey.io/valkey-helm/"
    condition: redis.enabled
