apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grounds-nats.fullname" . }}-keys
type: Opaque
stringData:
  auth-service.creds: |
{{ .Values.keys.authServiceCreds | indent 4 }}
  operator-xkey-private: "{{ .Values.keys.operatorXkeyPrivate | trim }}"
  account-signing-nkey: "{{ .Values.keys.accountSigningNkey | trim }}"
