{{- if eq (include "grounds-gamemode.serviceAccountRequired" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "grounds-gamemode.serviceAccountName" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    grounds/component: gamemode
  {{- if or .Values.serviceAccount.annotations .Values.global.commonAnnotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
