apiVersion: v1
kind: Service
metadata:
  name: {{ include "grounds-postgres-dev.fullname" . }}
spec:
  selector: { app: {{ include "grounds-postgres-dev.fullname" . }} }
  ports: [{ name: postgres, port: 5432, targetPort: 5432 }]
