{{- if or .Values.serviceAccount.create .Values.permissions.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-agones-sdk
  labels:
    {{- include "common.labels" . | nindent 4 }}
    grounds/component: velocity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk
subjects:
  - kind: ServiceAccount
    name: {{ include "grounds-velocity.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
