apiVersion: v2
name: plugin-velocity-jar
description: Hosts a Velocity-plugin JAR so the grounds-velocity proxy can fetch
  it at startup
type: application
version: 0.1.0

dependencies:
  - name: common
    version: "0.2.0"
    repository: "oci://ghcr.io/groundsgg/charts"
